create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  external_reference text not null unique,
  mercadopago_preference_id text,
  mercadopago_payment_id text,
  status text not null default 'preference_created',
  status_detail text,
  buyer_user_id uuid references auth.users(id) on delete set null,
  buyer_name text,
  buyer_email text,
  buyer_phone text,
  delivery_address text,
  delivery_notes text,
  currency text not null default 'ARS',
  shipping_cost numeric(12, 2) not null default 0,
  total_amount numeric(12, 2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  payment_method_id text,
  payment_type_id text,
  raw_payment jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

grant usage on schema public to service_role;
grant select, insert, update on public.orders to service_role;
grant select on public.orders to authenticated;

alter table public.orders add column if not exists buyer_user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists buyer_phone text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists delivery_notes text;
alter table public.orders add column if not exists shipping_cost numeric(12, 2) not null default 0;

create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists orders_buyer_email_idx on public.orders(buyer_email);
create index if not exists orders_buyer_user_id_idx on public.orders(buyer_user_id);

drop policy if exists "Users can read their own orders" on public.orders;
create policy "Users can read their own orders"
on public.orders
for select
to authenticated
using (auth.uid() = buyer_user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

create table if not exists public.products (
  id integer primary key generated by default as identity,
  nombre text not null,
  precio numeric(12, 2) not null check (precio > 0),
  categoria text not null,
  imagen text not null,
  descripcion text not null,
  precio_por text not null default '100gr',
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

grant select on public.products to anon, authenticated;
grant select, insert, update, delete on public.products to service_role;
grant usage, select on sequence public.products_id_seq to service_role;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products
for select
to anon, authenticated
using (activo = true);

insert into public.products (id, nombre, precio, categoria, imagen, descripcion, precio_por, activo)
values
  (1, 'Merluza', 1200, 'Pescado', '/imagenes/merluza.jpg', 'Merluza fresca del Atlántico Sur. Carne blanca y delicada, ideal para al horno o a la plancha.', '100gr', true),
  (2, 'Langostinos', 1800, 'Mariscos', '/imagenes/langostinos.jpg', 'Langostinos frescos de tamaño jumbo. Perfectos para parrilla, al ajillo o ceviche.', '100gr', true),
  (3, 'Calamar', 1400, 'Mariscos', '/imagenes/calamar.jpg', 'Calamar fresco entero. Excelente para rabas, a la romana o rellenos.', '100gr', true),
  (4, 'Corvina', 1500, 'Pescado', '/imagenes/corbina.jpg', 'Corvina negra fresca. Pescado de carne firme, ideal para cualquier preparación.', '100gr', true),
  (5, 'Salmón', 2200, 'Premium', '/imagenes/salmon.jpg', 'Filete de salmón rosado premium. Perfecto para sushi, parrilla o al horno.', '100gr', true),
  (6, 'Croquetas de Bacalao', 800, 'Elaborados', '/imagenes/croquetas_bacalao.jpg', 'Croquetas artesanales de bacalao. Listas para freír, crujientes por fuera y cremosas por dentro.', '100gr', true)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 0) from public.products), 1),
  true
);

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  email text not null,
  telefono text,
  mensaje text not null,
  status text not null default 'new',
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;

grant select, insert, update, delete on public.contact_messages to service_role;

create index if not exists contact_messages_created_at_idx on public.contact_messages(created_at desc);
create index if not exists contact_messages_status_idx on public.contact_messages(status);

drop trigger if exists contact_messages_set_updated_at on public.contact_messages;
create trigger contact_messages_set_updated_at
before update on public.contact_messages
for each row
execute function public.set_updated_at();
